### ISSUE TITLE
JS does not run in some versions of firefox

### ISSUE THREAD

**Issue by ifkb99** [zackatoo/qcbuilder#7]
Specifically Opensuse, will test on more

**Comment by zackatoo** [comment]
Also did not work on my version of Microsoft Edge, specifically version 44.17763.771.0

**Comment by ifkb99** [comment]
This seems to be the related error

https://stackoverflow.com/questions/56083707/how-to-fix-syntaxerror-fields-are-not-currently-supported-error-in-javascript
